"""Enumerations for L6 Multi-Gate Validation Layer."""

from enum import Enum


class ValidationDecision(str, Enum):
    APPROVED = "APPROVED"
    BLOCKED = "BLOCKED"


class GateStatus(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    SKIPPED = "SKIPPED"


class ViolationCode(str, Enum):
    # Gate 1 — Structural
    UNAUTHORIZED_TABLE = "UNAUTHORIZED_TABLE"
    UNAUTHORIZED_COLUMN = "UNAUTHORIZED_COLUMN"
    RESTRICTED_JOIN = "RESTRICTED_JOIN"
    MISSING_REQUIRED_FILTER = "MISSING_REQUIRED_FILTER"
    AGGREGATION_VIOLATION = "AGGREGATION_VIOLATION"
    WILDCARD_UNAUTHORIZED_COLUMN = "WILDCARD_UNAUTHORIZED_COLUMN"
    UNAUTHORIZED_CTE_REFERENCE = "UNAUTHORIZED_CTE_REFERENCE"
    EXCESSIVE_SUBQUERY_DEPTH = "EXCESSIVE_SUBQUERY_DEPTH"
    UNPARSEABLE_SQL = "UNPARSEABLE_SQL"

    # Gate 2 — Classification
    SENSITIVITY_EXCEEDED = "SENSITIVITY_EXCEEDED"
    UNMASKED_PII_COLUMN = "UNMASKED_PII_COLUMN"
    AGGREGATE_ON_PII = "AGGREGATE_ON_PII"
    PII_IN_FILTER_LITERAL = "PII_IN_FILTER_LITERAL"
    STALE_CLASSIFICATION = "STALE_CLASSIFICATION"

    # Gate 3 — Behavioral
    WRITE_OPERATION = "WRITE_OPERATION"
    SYSTEM_TABLE_ACCESS = "SYSTEM_TABLE_ACCESS"
    UNION_EXFILTRATION = "UNION_EXFILTRATION"
    DYNAMIC_SQL = "DYNAMIC_SQL"
    STACKED_QUERIES = "STACKED_QUERIES"
    CARTESIAN_PRODUCT = "CARTESIAN_PRODUCT"
    FILE_OPERATION = "FILE_OPERATION"
    PRIVILEGE_ESCALATION = "PRIVILEGE_ESCALATION"
    COMMENT_INJECTION = "COMMENT_INJECTION"
    EXCESSIVE_COLUMNS = "EXCESSIVE_COLUMNS"

    # Rewriter errors
    MASKING_REWRITE_FAILURE = "MASKING_REWRITE_FAILURE"
    REWRITER_ERROR = "REWRITER_ERROR"

    # Orchestrator / envelope errors
    INVALID_ENVELOPE = "INVALID_ENVELOPE"


class ViolationSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class SQLDialect(str, Enum):
    POSTGRESQL = "postgresql"
    MYSQL = "mysql"
    TSQL = "tsql"
    ORACLE = "oracle"


class RewriteType(str, Enum):
    MASKING = "MASKING"
    WHERE_FILTER = "WHERE_FILTER"
    LIMIT = "LIMIT"
    WILDCARD_EXPANSION = "WILDCARD_EXPANSION"
    COMMENT_STRIP = "COMMENT_STRIP"
