apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinelsql-config
  namespace: sentinelsql
data:
  # Base Environment
  APP_ENV: "production"
  
  # Identity configuration
  USE_MOCK_IDP: "true"
  IDP_JWKS_URI: "https://dev.okta.com/oauth2/v1/keys"
  IDP_ISSUER: "https://dev.okta.com"
  IDP_AUDIENCE: "api://sentinelsql"
  CORS_ORIGINS: "http://sentinelsql.yourdomain.com,https://sentinelsql.yourdomain.com"
  
  # Neo4j Database
  NEO4J_URI: "neo4j+s://5ddec823.databases.neo4j.io"
  NEO4J_DATABASE: "5ddec823"
  NEO4J_ENCRYPTED: "true"
  
  # Aiven Postgres
  AIVEN_PG_HOST: "pg-hospital-system-hospital-syatem.k.aivencloud.com"
  AIVEN_PG_PORT: "21400"
  POSTGRES_HOST: "pg-hospital-system-hospital-syatem.k.aivencloud.com"  # L7 field name
  POSTGRES_USER: "avnadmin"  # L7 field name
  POSTGRES_DBNAME_ANALYTICS: "apollo_analytics"
  POSTGRES_DBNAME_FINANCIAL: "apollo_financial"
  POSTGRES_SSLMODE: "require"
  
  # Aiven MySQL
  MYSQL_HOST: "mysql-hospital-system-hospital-syatem.k.aivencloud.com"
  MYSQL_PORT: "21400"
  MYSQL_DBNAME_HIS: "ApolloHIS"
  MYSQL_DBNAME_HR: "ApolloHR"
  MYSQL_SSL: "true"

  # Azure OpenAI
  AZURE_AI_ENDPOINT: "https://anndocextopenai.cognitiveservices.azure.com/"
  AZURE_OPENAI_DEPLOYMENT: "gpt-4.1"
  AZURE_OPENAI_FALLBACK_DEPLOYMENT: "gpt-4.1-mini"
  
  # Redis URL
  REDIS_URL: "redis://redis.sentinelsql.svc.cluster.local:6379/0"
  L1_REDIS_URL: "redis://redis.sentinelsql.svc.cluster.local:6379/0"
  
  # Vault (If used)
  VAULT_ADDR: "http://vault:8200"
