apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinelsql-config
  namespace: sentinelsql
data:
  AIVEN_PG_HOST: "REPLACE_WITH_AIVEN_PG_HOST"
  AIVEN_PG_PORT: "REPLACE_WITH_AIVEN_PG_PORT"
  APP_ENV: "REPLACE_WITH_APP_ENV"
  AZURE_AI_ENDPOINT: "REPLACE_WITH_AZURE_AI_ENDPOINT"
  AZURE_OPENAI_DEPLOYMENT: "REPLACE_WITH_AZURE_OPENAI_DEPLOYMENT"
  AZURE_OPENAI_FALLBACK_DEPLOYMENT: "REPLACE_WITH_AZURE_OPENAI_FALLBACK_DEPLOYMENT"
  CORS_ORIGINS: "REPLACE_WITH_CORS_ORIGINS"
  IDP_AUDIENCE: "REPLACE_WITH_IDP_AUDIENCE"
  IDP_ISSUER: "REPLACE_WITH_IDP_ISSUER"
  IDP_JWKS_URI: "REPLACE_WITH_IDP_JWKS_URI"
  MYSQL_DBNAME_HIS: "REPLACE_WITH_MYSQL_DBNAME_HIS"
  MYSQL_DBNAME_HR: "REPLACE_WITH_MYSQL_DBNAME_HR"
  MYSQL_HOST: "REPLACE_WITH_MYSQL_HOST"
  MYSQL_PORT: "REPLACE_WITH_MYSQL_PORT"
  MYSQL_SSL: "REPLACE_WITH_MYSQL_SSL"
  NEO4J_DATABASE: "REPLACE_WITH_NEO4J_DATABASE"
  NEO4J_USERNAME: "REPLACE_WITH_NEO4J_USERNAME"
  NEO4J_READ_USER: "REPLACE_WITH_NEO4J_READ_USER"
  NEO4J_WRITE_USER: "REPLACE_WITH_NEO4J_WRITE_USER"
  NEO4J_ENCRYPTED: "REPLACE_WITH_NEO4J_ENCRYPTED"
  NEO4J_URI: "REPLACE_WITH_NEO4J_URI"
  POSTGRES_DBNAME_ANALYTICS: "REPLACE_WITH_POSTGRES_DBNAME_ANALYTICS"
  POSTGRES_DBNAME_FINANCIAL: "REPLACE_WITH_POSTGRES_DBNAME_FINANCIAL"
  POSTGRES_SSLMODE: "REPLACE_WITH_POSTGRES_SSLMODE"
  USE_MOCK_IDP: "REPLACE_WITH_USE_MOCK_IDP"
  VAULT_ADDR: "REPLACE_WITH_VAULT_ADDR"
  
  SENTINELSQL_PUBLIC_KEY: |
    REPLACE_WITH_SENTINELSQL_PUBLIC_KEY

