controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-dns-label-name: sentinelsql
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthcheck
  config:
    server-snippet: |
      location /healthcheck {
        return 200 'ok';
        add_header Content-Type text/plain;
      }
