apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: sentinelsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        workload: sentinelsql
      tolerations:
        - key: dedicated
          operator: Equal
          value: sentinelsql
          effect: NoSchedule
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: sentinelsql
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
